import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'dart:typed_data';

import 'package:susu_micro/models/transaction_model.dart';
import 'package:susu_micro/utils/helpers.dart';


Future<Uint8List> generateTransactionStatement(Transaction tx) async {
  final pdf = pw.Document();
  final font = await PdfGoogleFonts.openSansRegular();
final boldFont = await PdfGoogleFonts.openSansBold();
  logs.d("Generating PDF for transaction: ${tx.id}");
  pdf.addPage(
    pw.Page(
      pageFormat: PdfPageFormat.a4,
      build: (context) {
        return pw.Container(
          padding: const pw.EdgeInsets.all(24),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text("Transaction Statement",
                  style: pw.TextStyle(
                    fontSize: 24,
                    font: boldFont,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blue700,
                  )),
              pw.SizedBox(height: 20),
              pw.Text("Transaction ID: ${tx.id}"),
              pw.Text("Account: ${tx.accountType}"),
              pw.Text("Account Holder: ${tx.customerName}"),
              pw.Text("Amount: ${tx.amount}"),
              pw.Text("Type: ${tx.type}"),
              pw.Text("Status: ${tx.status}"),
              pw.Text("Staff: ${tx.staffName}"),
              pw.Text("Date: ${tx.transactionDate}"),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.Text(
                "Generated by SusuPro",
                style: pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          ),
        );
      },
    ),
  );

  return pdf.save();
}
